tactigon_shapes/modules/braccio/models.py
from enum import Enum
from dataclasses import dataclass

from typing import Optional

class Wrist(Enum):
    HORIZONTAL = 90
    VERTICAL = 0

class Gripper(Enum):
    OPEN = 0
    CLOSE = 73

class Command(Enum):
    MOVE = "P"
    HOME = "H"
    TURN_ON = "1"
    TURNO_OFF = "0"

class CommandStatus(Enum):
    EXECUTING = "100"
    OK = "0"
    ERROR_1 = "1"
    ERROR_2 = "2"
    OUT_OF_RANGE = "3"
    TIMEOUT = "99"

@dataclass
class BraccioConfig:
    name: str
    address: str

    @classmethod
    def FromJSON(cls, json: dict):
        return cls(
                json["name"],
                json["address"],
            )
        
    def toJSON(self) -> object:
        return {
            "name": self.name,
            "address": self.address
        }

@dataclass
class BraccioPosition:
    base: float
    shoulder: float
    elbow: float
    wrist: float
    wrist_rotation: Wrist
    gripper: Gripper

    def toString(self):
        return f"{self.base},{self.shoulder},{self.elbow},{self.wrist},{self.wrist_rotation.value},{self.gripper.value}"

@dataclass
class BraccioCommand:
    command: Command
    position: Optional[BraccioPosition] = None

    @classmethod
    def Move(cls, position):
        return cls(Command.MOVE, position)
    
    @classmethod
    def Home(cls):
        return cls(Command.HOME)
    
    @classmethod
    def On(cls):
        return cls(Command.TURN_ON)
    
    @classmethod
    def Off(cls):
        return cls(Command.TURNO_OFF)

    def toString(self):
        pos_string = "," + self.position.toString() if self.position else ""
        return f"{self.command.value}{pos_string}"

tactigon_shapes/modules/braccio/blueprint.py
import sys
import json
import asyncio
from bleak import BleakScanner
from flask import Blueprint, render_template, redirect, url_for, flash

from .extension import BraccioConfig, BraccioInterface
from .manager import get_braccio_interface

from ...config import check_config
from ...utils.extensions import stop_apps
from ...utils.request_utils import get_from_request

bp = Blueprint("braccio", __name__, url_prefix="/braccio", template_folder="templates")

@bp.before_request
def manage():
    stop_apps(BraccioInterface.__name__)

@bp.route("/")
@check_config
def index():
    app = get_braccio_interface()

    if not app:
        flash("Braccio interface not running", category="danger")
        return redirect(url_for("main.index"))

    return render_template("braccio/index.jinja", configured=app.configured, config=app.config)

if sys.platform == "darwin":
    @bp.route("scan")
    @check_config
    def scan():
        app = get_braccio_interface()

        if not app:
            flash("Braccio interface not running", category="danger")
            return redirect(url_for("main.index"))
        
        async def find_devices():
            devices = await BleakScanner.discover(cb=dict(use_bdaddr=True))
            return filter(lambda d: str(d.name).startswith("ADA"), devices)

        devices = [{"name": d.name, "id": d.address, "address": str(d.details[0].identifier())} for d in asyncio.run(find_devices())]

        return json.dumps(devices)
else:
    @bp.route("/scan")
    @check_config
    def scan():
        app = get_braccio_interface()

        if not app:
            flash("Braccio interface not running", category="danger")
            return redirect(url_for("main.index"))
        
        async def find_devices():
            devices = await BleakScanner.discover()
            return filter(lambda d: str(d.name).startswith("ADA") , devices)

        devices = [{"name": d.name, "id": d.address, "address": d.address} for d in asyncio.run(find_devices())]

        return json.dumps(devices)

@bp.route("/save", methods=["POST"])
@check_config
def save():
    app = get_braccio_interface()

    if not app:
        flash("Braccio interface not running", category="danger")
        return redirect(url_for("main.index"))
    
    name = get_from_request("name")
    address = get_from_request("address")

    if name is None:
        flash("Cannot save Braccio configurations. Name missing", category="danger")
        return redirect(url_for("braccio.index"))
    
    if address is None:
        flash("Cannot save Braccio configurations. Address missing", category="danger")
        return redirect(url_for("braccio.index"))
    
    new_config = BraccioConfig(name, address)
    app.save_config(new_config)

    flash("Braccio configured succesfully", category="success")
    return redirect(url_for("braccio.index"))

@bp.route("/remove")
@check_config
def remove():
    app = get_braccio_interface()

    if not app:
        flash("Braccio interface not running", category="danger")
        return redirect(url_for("main.index"))

    app.reset_config()

    flash("Braccio configuration removed!", category="success")
    return redirect(url_for("braccio.index"))

@bp.route("/start")
@check_config
def start():
    app = get_braccio_interface()

    if not app:
        flash("Braccio interface not running", category="danger")
        return redirect(url_for("main.index"))
    
    if app.config is None:
        flash("Invalid configuration", category="danger")
        return redirect(url_for("braccio.index"))
    
    app.start()
    flash("Braccio started!", category="success")
    return redirect(url_for("braccio.index"))

@bp.route("/stop")
def stop():
    app = get_braccio_interface()

    if not app:
        flash("Braccio interface not running", category="danger")
        return redirect(url_for("main.index"))
    
    app.stop()
    flash("Braccio stopped", category="success")
    return redirect(url_for("braccio.index"))

tactigon_shapes/modules/braccio/middleware/__init__.py
__all__ = ["Solver"]

from ..middleware.solver import Solver

tactigon_shapes/modules/braccio/templates/braccio/index.jinja
{% extends "base.jinja" %}

{% block style %}
{% endblock %}

{% block body %}
<div class="d-flex flex-fill scrollarea">
    <div class="container my-3">
        <div class="card">
            <div class="card-header">
                Braccio configurations
                {% if configured and not braccio_status %}
                    <div class="float-end">
                        <button type="button" class="btn btn-link text-decoration-none p-0 text-danger" data-bs-toggle="modal" data-bs-target="#remove_braccio" title="Delete">
                            <i class="mi-round mi-delete-forever"></i>
                        </button>
                    </div>
                    <div class="modal fade" id="remove_braccio" tabindex="-1">
                        <div class="modal-dialog">
                            <div class="modal-content text-dark">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="staticBackdropLabel">Braccio</h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body d-flex flex-column gap-3">
                                    <h4>Warning!</h4>
                                    You are about to remove Braccio. Are you sure?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Close</button>
                                    <a href="{{ url_for('braccio.remove')}}" class="btn btn-primary">
                                        Remove
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
            <div class="card-body pb-4">
                <div class="d-flex flex-column align-items-center gap-3">
                    <i class="mi-outlined mi-precision-manufacturing" style="font-size: 124px"></i>
                    {% if configured %}
                        {% if not braccio_status %}
                            <a href="{{ url_for('braccio.start') }}" class="btn btn-primary">Start braccio</a>
                        {% else %}
                            <a href="{{ url_for('braccio.stop') }}" class="btn btn-outline-secondary">Stop braccio</a>
                        {% endif %}
                        <p>
                            Status: {% if braccio_status %}Running{% else %}Stopped{% endif %} <br>
                            Name: {{ config.name }} <br>
                            Address: {{ config.address }}
                        </p>
                        {% if not braccio_status %}
                            <button type="button" class="btn btn-outline-danger btn-sm" data-bs-toggle="modal" data-bs-target="#remove_braccio">Remove braccio</button>
                        {% endif %}
                    {% else %}
                        <p class="mx-auto" id="searching">
                            We are looking for your Braccio...
                        </p>
                        <div class="spinner-border text-primary mx-auto" id="loading" role="status">
                            <span class="visually-hidden">Loading...</span>
                        </div>
                        <form action="{{ url_for('braccio.save') }}" class="d-none" id="add_form" method="POST">
                            <div class="mb-3">
                                <label for="name" class="form-label">Name</label>
                                <input type="text" class="form-control" id="name" aria-describedby="emailHelp" name="name">
                            </div>
                            <div class="mb-3">
                                <label for="address" class="form-label">Bluetooth address</label>
                                <div class="input-group">
                                    <select id="address" name="address" class="form-select">
                                    </select>
                                    <button class="btn btn-outline-secondary" type="button" id="refresh_button_form">Refresh</button>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary btn-block">Save</button>
                        </form>
                        <div class="d-flex flex-column justify-content-center gap-3 d-none mb-3" id="refresh">
                            <p class="mx-auto">Ops, we couldn't find any Braccio.</p>
                            <div class="d-flex flex-column">
                                <small class="mx-auto text-muted">Check that the Bluetooth is enabled</small>
                                <small class="mx-auto text-muted">and Braccio is nearby</small>
                            </div>
                        </div>
                        <button type="button" class="mx-auto btn btn-outline-tskin d-none" id="refresh_button">
                            <i class="bi bi-arrow-clockwise"></i>
                            Search again
                        </button>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    function scan(){
        $("#loading, #searching").removeClass("d-none");
        $("#add_form, #refresh, #refresh_button").addClass("d-none");
        
        $.getJSON("{{ url_for('braccio.scan') }}")
            .then(function(data){
                console.log(data)
                if (data.length == 0){
                    $("#refresh").removeClass("d-none");
                    return false;
                }

                return data;
            })
            .fail(function(err){
                $("#loading, #searching").addClass("d-none");
                $("#refresh").removeClass("d-none");
            })
            .done(function(result){
                $("#loading, #searching, #refresh").addClass("d-none");
                
                if (!result){
                    $("#loading, #searching").addClass("d-none");
                    $("#refresh, #refresh_button").removeClass("d-none");
                    return;
                }

                const options = $.map(result, function(device, i){
                    return $("<option/>", {value: device.address}).html(device.name + " (" + device.id + ")");
                });

                $("#address").html(options);
                $("#add_form").removeClass("d-none");

                // const devices = $.map(result, function(device, i){
                //     return $("<button/>", {type: "button", class: "list-group-item list-group-item-action"}).append([
                //         $("<div/>", {class: "d-flex gap-3 py-3 align-items-center"}).append([
                //             $("<i/>", {class: "mi-round mi-precision-manufacturing", style: "font-size: 24px;"}),
                //             $("<div/>").append([
                //                 $("<h6/>", {class: "mb-0"}).html(`${device.name}`),
                //                 $("<small/>", {class: "mb-0 opacity-75"}).html(device.id)
                //             ])
                //             // Todo, battery
                //         ])
                //     ]).click(function(){
                //         save(device.address, device.name);
                //     });
                    
                // })

                // $("#list").html(devices).removeClass("d-none");
                // $("#refresh_button").removeClass("d-none");
            });
    }

    // function save(address, name){
    //     $("#found-1").addClass("d-none");
    //     $("setting-up").removeClass("d-none");
    //     $.post("{{ url_for('braccio.save') }}", {name: name, address: address})
    //         .fail((error)=>{
    //             window.location.href = "{{ url_for('braccio.index') }}";
    //         })
    //         .done((data)=>{
    //             window.location.href = "{{ url_for('braccio.index') }}";
    //         });
    // }

    $(()=>{
        {% if not configured %}
            scan();
        {% endif %}

        $("#refresh_button, #refresh_button_form").click(function(e){
            scan();
        })
    });
</script>
{% endblock %}