tactigon_shapes/modules/tskin/models.py
import sys
import json
from os import path
from datetime import datetime
from dataclasses import dataclass
from typing import Optional, List, Tuple, Iterable

from tactigon_gear import TSkinConfig, GestureConfig, Gesture, Hand, Angle, Touch, OneFingerGesture, TwoFingerGesture

if sys.platform != "darwin":
    from tactigon_speech import TSkin_Speech as OldTSkin, VoiceConfig as OldVoiceConfig, Transcription, TSpeech, TSpeechObject, HotWord
else:
    from tactigon_gear import TSkin as OldTSkin
    tactigon_speech_version = None

if sys.platform != "darwin":
    HotWords = Tuple[HotWord, Optional[Iterable["HotWords"]]]

    @dataclass
    class TranscriptionWithPath(Transcription):
        @classmethod
        def FromTranscription(cls, transcription: Transcription):
            return TranscriptionWithPath(
                transcription.text,
                transcription.path,
                transcription.time,
                transcription.timeout
            )

        def filter_tree(self, tree: Optional[TSpeechObject]) -> Optional[TSpeechObject]:
            def f(tree: Optional[TSpeechObject], tree_path: List[HotWord]) -> Optional[TSpeechObject]:
                if not tree:
                    return

                if not tree_path:
                    return tree

                node, *rest = tree_path

                branches = [branch.children for branch in tree.t_speech if node in branch.hotwords]

                if not branches:
                    return tree

                filtered_tree, *_ = branches

                return f(filtered_tree, rest)

            return f(tree, self.path) if self.path else tree
        
        def __str__(self):
            return F"TranscriptionWithPath {self.text}, Path: {', '.join([hw.word for hw in self.path] if self.path else [])}, Time: {self.time}, Timeout: {self.timeout}"
        
    @dataclass
    class VoiceConfig(OldVoiceConfig):
        voice_commands_notification: Optional[str] = path.join("config", "audio", "trigger.wav")
        voice_commands: Optional[TSpeechObject] = None

        stop_hotword = None # type: ignore

        @classmethod
        def FromJSON(cls, json: dict):
            _t = super().FromJSON(json)
            _t.stop_hotword = None # type: ignore
            _t.voice_commands = TSpeechObject.FromJSON(json["voice_commands"]) if "voice_commands"in json and json["voice_commands"] else None
            _t.voice_commands_notification = json["voice_commands_notification"] if "voice_commands_notification" in json else None
            return _t
        
        def toJSON(self) -> dict:
            d = super().toJSON()
            d["voice_commands"] = self.voice_commands.toJSON() if self.voice_commands else None
            d["voice_commands_notification"] = self.voice_commands_notification
            return d

    class TSkin(OldTSkin):
        def __init__(self, config: TSkinConfig, voice_config: Optional[VoiceConfig], debug: bool = False):
            if voice_config is None:
                raise ValueError("Missing the configuration for the voice")
            
            OldTSkin.__init__(self, config, voice_config, debug=debug)

        @property
        def can_listen(self):
            return True

else:
    @dataclass
    class VoiceConfig:
        @classmethod
        def FromJSON(cls, json: dict):
            return cls()
        
        def toJSON(self) -> dict:
            return {}
        
    @dataclass
    class HotWord:
        @classmethod
        def FromJSON(cls, json: dict):
            return cls()
        
        def toJSON(self) -> dict:
            return {}
        
    HotWords = Tuple[HotWord, Optional[Iterable["HotWords"]]]
        
    @dataclass
    class TSpeechObject:
        @classmethod
        def FromJSON(cls, json: dict):
            return cls()
        
        def toJSON(self) -> dict:
            return {}
        
    class TSkin(OldTSkin):
        def __init__(self, config: TSkinConfig, voice: Optional[VoiceConfig], debug: bool = False):
            OldTSkin.__init__(self, config, debug)

        @property
        def touch_preserve(self) -> Optional[Touch]:
            self._update_touch.acquire()
            touch = self._touch
            self._update_touch.release()
            return touch

@dataclass
class ModelGesture:
    gesture: str
    label: str
    description: Optional[str] = None

    @classmethod
    def FromJSON(cls, json: dict):
        return cls(
            json["gesture"],
            json["label"],
            json["description"] if "description" in json and json["description"] else None
        )

    def toJSON(self) -> dict:
        return {
            "gesture": self.gesture,
            "label": self.label,
        }

@dataclass
class ModelTouch:
    gesture: OneFingerGesture
    label: str
    description: Optional[str] = None

    @classmethod
    def FromJSON(cls, json: dict):
        return cls(
            OneFingerGesture(json["gesture"]),
            json["label"],
            json["description"] if "description" in json and json["description"] else None
        )
    
    def toJSON(self) -> dict:
        return {
            "gesture": self.gesture.value,
            "label": self.label
        }

@dataclass
class TSkinModel:
    name: str
    hand: Hand
    date: datetime
    gestures: List[ModelGesture]
    touchs: List[ModelTouch]

    @classmethod
    def FromJSON(cls, json: dict):
        return cls(
            json["name"],
            Hand(json["hand"]),
            datetime.fromisoformat(json["date"]),
            [ModelGesture.FromJSON(g) for g in json["gestures"]],
            [ModelTouch.FromJSON(g) for g in json["touchs"]],
        )
    
    def toJSON(self):
        return {
            "name": self.name,
            "hand": self.hand.value,
            "date": self.date.isoformat(),
            "gestures": [g.toJSON() for g in self.gestures],
            "touchs": [t.toJSON() for t in self.touchs]
        }

tactigon_shapes/modules/tskin/blueprint.py
import sys
import json
import asyncio
from os import path
from bleak import BleakScanner
from flask import Blueprint, render_template, redirect, url_for, request, flash, current_app
from typing import Optional

from .manager import get_tskin_default_config, get_voice_default_config, start_tskin, load_tskin, stop_tskin, get_tskin
from .models import TSkinModel, VoiceConfig, TSkinConfig, Hand, GestureConfig, TSpeechObject, TSpeech, HotWord

from ..socketio import get_socket_app
from ...config import app_config
from ...utils.extensions import stop_apps
from ...utils.request_utils import get_from_request

bp = Blueprint('tskin', __name__, url_prefix="/tskin", template_folder="templates")

@bp.before_request
def manage():
    stop_apps()

@bp.route("add", methods=["GET"])
def add():
    return render_template("tskin/add.jinja")

if sys.platform == "darwin":
    @bp.route("scan", methods=["GET"])
    def scan():
        async def find_devices():
            devices = await BleakScanner.discover(cb=dict(use_bdaddr=True))
            return filter(lambda d: str(d.name).startswith("TSKIN") or str(d.name).startswith("TACTI"), devices)

        devices = asyncio.run(find_devices())
        tskins = [{"name": d.name, "id": d.address, "address": str(d.details[0].identifier())} for d in devices]
        
        return json.dumps(tskins)
else:
    @bp.route("scan", methods=["GET"])
    def scan():
        async def find_devices():
            devices = await BleakScanner.discover()
            return filter(lambda d: str(d.name).startswith("TSKIN") , devices)

        devices = asyncio.run(find_devices())
        tskins = [{"name": d.name, "id": d.address, "address": d.address} for d in devices]

        return json.dumps(tskins)

@bp.route("hand", methods=["POST"])
def hand():
    tskin_name = get_from_request("tskin_name")
    tskin_mac = get_from_request("tskin_mac")

    if not (tskin_mac and tskin_name):
        flash("You need to select a Tactigon Skin to proceed", category="danger")
        return redirect(url_for("tskin.add"))

    return render_template("tskin/hand.jinja", tskin_name=tskin_name, tskin_mac=tskin_mac)

@bp.route("model", methods=["POST"])
def model():
    tskin_name = get_from_request("tskin_name")
    tskin_mac = get_from_request("tskin_mac")

    if not tskin_name or not tskin_mac:
        return redirect(url_for("tskin.add"))

    hand = get_from_request("hand")

    if not hand:
        flash("Please select a hand", "danger")
        return redirect(url_for("tskin.add"))

    models = list(filter(lambda m: m.hand.value==hand, app_config.MODELS))

    if len(models) == 1:
        return redirect(url_for("tskin.save", tskin_name=tskin_name, tskin_mac=tskin_mac, hand=hand, model=models[0].name), code=307)

    return render_template("tskin/model.jinja", tskin_name=tskin_name, tskin_mac=tskin_mac, hand=hand, models=models)

@bp.route("/remove", methods=["GET"])
def remove():
    socket_app = get_socket_app()

    tskin = get_tskin()

    if tskin is None:
        flash(F"Tactigon skin {hand} not configured!", "danger")
        return redirect(url_for("main.index"))

    if socket_app:
        socket_app.stop()
    
    stop_tskin()

    app_config.TSKIN = None
    app_config.TSKIN_VOICE = None
    
    app_config.save()
    current_app.config.from_object(app_config)

    if socket_app:
        socket_app.init_app(current_app)

    return redirect(url_for("main.index"))

@bp.route("save", methods=["POST"])
def save():
    socket_app = get_socket_app()

    tskin_name = get_from_request("name")
    tskin_mac = get_from_request("mac")

    if not tskin_name or not tskin_mac:
        flash("Please select a Tactigon Skin", "danger")
        return {"error": "name or mac error"}, 500

    hand = get_from_request("hand")
    
    if not hand:
        flash("Please select a hand", "danger")
        return {"error": "hand error"}, 500

    # if not model_name:
    #     flash("Please select a model", "danger")
    #     return redirect(url_for("tskin.add", tskin_name=tskin_name, tskin_mac=tskin_mac, hand=hand), code=307)
        
    hand = Hand(hand)
    model_name = "MODEL_01_" + hand.name

    current_model: Optional[TSkinModel] = None

    for model in app_config.MODELS:
        if model.name == model_name:
            current_model = model
            break

    if current_model is None:
        flash("Error MODEL", "danger")
        return {"error": "model error"}, 500
        # return redirect(url_for("tskin.add"))
    
    tskin_config = get_tskin_default_config(tskin_mac, hand, tskin_name, current_model)
    voice_config = get_voice_default_config()

    if voice_config:
        voice_config.stop_hotword = None

    if socket_app:
        socket_app.stop()

    stop_tskin()
    app_config.TSKIN = tskin_config
    app_config.TSKIN_VOICE = voice_config

    app_config.save()
    current_app.config.from_object(app_config)

    load_tskin(tskin_config, voice_config)
    tskin = start_tskin()

    if socket_app and tskin:
        socket_app.setTSkin(tskin)

    return json.dumps(tskin_config.toJSON()), 200

if sys.platform != "darwin":
    @bp.route("play", methods=["POST"])
    def play(base_path = ""):
        tskin = get_tskin()

        if not tskin:
            return "Error: TSkin not present"
        
        data = request.get_json(force=True)

        if not data:
            return "Error: No JSON in request"
        
        audio_file = data.get("audio_file")

        if not audio_file:
            return "Error: No audio_file in JSON"
        
        base_path = data.get("base_path")

        if base_path:
            audio_file = path.join(base_path, audio_file)

        tskin.play(audio_file)

        return "Ok"
else:
    @bp.route("play", methods=["POST"])
    def play(base_path = ""):
        return "Not Implemented", 500

tactigon_shapes/modules/tskin/templates/tskin/hand.jinja
{% extends "base.jinja" %}

{% block style %}
    <style>
        .hand {

        }
    </style>
{% endblock %}

{% block body %}
<div class="d-flex flex-fill scrollarea">
    <div class="container my-3">
        <form id="hand_form" action="{{ url_for('tskin.model') }}" method="POST">
            <div class="card">
                <div class="card-header">
                    Tactigon Skin configuration
                </div>
                <div class="card-body">
                    <h3 class="text-center">HAND SELECTION</h3>
                    <h5 class="text-muted text-center">Are you using the Tactigon Skin on the left or on the right hand?</h5>
                    <hr>

                    <div class="d-flex gap-5 justify-content-center">
                        <div class="d-flex flex-column">
                            <label for="left">
                                <svg version="1.1" name="svg-hands" id="left-hand-svg" width="217" height="294" viewBox="0 0 106.38618 141.13435" xmlns="http://www.w3.org/2000/svg">
                                    <defs>
                                        <filter style="color-interpolation-filters:sRGB"
                                            id="left-selection-filter"
                                            x="-0.028983135"
                                            y="-0.021539411"
                                            width="1.0579988"
                                            height="1.0430788">
                                            <feGaussianBlur stdDeviation="0.58994719"/>
                                        </filter>
                                    </defs>
                                    <path
                                        style="mix-blend-mode:normal;fill:none;stroke:#EB6152;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:none;stroke-opacity:0.368293;filter:url(#left-selection-filter)"
                                        class="d-none"
                                        d="m 55.894294,135.33972 c 0.045,-16.28019 9.84908,-24.3886 21.62993,-37.28802 2.96017,-3.241235 3.52495,-6.684535 6.14898,-10.200545 3.10147,-4.15572 7.64263,-9.23847 10.09495,-13.80809 1.883333,-3.50949 4.964145,-4.10255 7.286846,-7.14276 l -0.46557,-0.93115 c -2.146421,-3.91082 -5.748026,-4.03084 -9.551726,-2.67276 -7.08296,2.52947 -10.66578,5.61038 -16.52042,13.80325 -2.01356,2.81735 -8.6857,3.92751 -10.80524,1.7784 -4.08657,-4.1437 -3.61085,-10.66342 -4.05329,-16.1679 -1.22316,-15.21823 2.8357,-30.3342 0.35169,-45.62628 -1.2332,-7.5923201 -6.21884,-11.03304 -10.09356,-6.4888 -2.21921,2.60291 -0.81717,8.72248 -1.0481,12.07569 -0.24442,3.55457 -0.65227,7.18018 -1.15881,10.70821 -0.87855,6.11751 -0.8365,17.94927 -3.21326,18.84524 -2.06976,-0.60448 -0.95735,-9.01273 -1.21482,-12.79278 -0.62387,-9.16827 -1.86416,-18.30726 -2.71663,-27.46887 -0.30913,-3.3214101 -0.88551,-8.36239 -3.8084,-10.36262 -4.43924,-3.03833 -7.24285,0.5542 -7.39331,6.6380199 -0.2137,8.5977601 -0.004,17.4568901 -0.007,26.0721601 -10e-4,3.85942 1.59599,17.01135 0.44607,17.60192 -1.08764,-0.23102 -2.25342,-12.97374 -2.70177,-16.67077 -0.83943,-6.92379 -1.35901,-14.62611 -2.55321,-21.41642 -0.55264,-3.14201 -3.05231,-6.0071201 -6.34484,-4.3873801 -3.92107,1.9290601 -3.85729,8.9820001 -3.41174,12.7677101 0.98144,8.34776 0.67788,16.78563 1.86882,25.14101 0.5559,3.90059 1.66877,10.5775 0.59175,11.17379 -1.22072,-0.14551 -2.63702,-8.5512 -4.32193,-12.5705 -1.71471,-4.09087 -2.35814,-8.78343 -3.9690197,-13.03609 -0.94279,-2.48984 -2.3781498,-7.59402 -6.0915848,-5.57217 -2.49639996,1.35933 -2.53596996,4.99594 -2.24545996,7.43447 0.80869996,6.78077 2.45543996,13.40854 4.11661496,20.0197 3.0201798,12.02344 3.0495098,24.52226 5.2595898,36.78036 2.7301297,15.141875 7.7173597,28.576485 7.7173597,44.229555"
                                        id="left-selection"/>
                                    <path
                                        style="fill:none;stroke:#494949;stroke-width:0.999495;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:none"
                                        d="m 55.894294,135.33972 c 0.045,-16.28019 9.84908,-24.3886 21.62993,-37.28802 2.96017,-3.241235 3.52495,-6.684535 6.14898,-10.200545 3.10147,-4.15572 7.64263,-9.23847 10.09495,-13.80809 1.883333,-3.50949 4.964145,-4.10255 7.286846,-7.14276 l -0.46557,-0.93115 c -2.146421,-3.91082 -5.748026,-4.03084 -9.551726,-2.67276 -7.08296,2.52947 -10.66578,5.61038 -16.52042,13.80325 -2.01356,2.81735 -8.6857,3.92751 -10.80524,1.7784 -4.08657,-4.1437 -3.61085,-10.66342 -4.05329,-16.1679 -1.22316,-15.21823 2.8357,-30.3342 0.35169,-45.62628 -1.2332,-7.5923201 -6.21884,-11.03304 -10.09356,-6.4888 -2.21921,2.60291 -0.81717,8.72248 -1.0481,12.07569 -0.24442,3.55457 -0.65227,7.18018 -1.15881,10.70821 -0.87855,6.11751 -0.8365,17.94927 -3.21326,18.84524 -2.06976,-0.60448 -0.95735,-9.01273 -1.21482,-12.79278 -0.62387,-9.16827 -1.86416,-18.30726 -2.71663,-27.46887 -0.30913,-3.3214101 -0.88551,-8.36239 -3.8084,-10.36262 -4.43924,-3.03833 -7.24285,0.5542 -7.39331,6.6380199 -0.2137,8.5977601 -0.004,17.4568901 -0.007,26.0721601 -10e-4,3.85942 1.59599,17.01135 0.44607,17.60192 -1.08764,-0.23102 -2.25342,-12.97374 -2.70177,-16.67077 -0.83943,-6.92379 -1.35901,-14.62611 -2.55321,-21.41642 -0.55264,-3.14201 -3.05231,-6.0071201 -6.34484,-4.3873801 -3.92107,1.9290601 -3.85729,8.9820001 -3.41174,12.7677101 0.98144,8.34776 0.67788,16.78563 1.86882,25.14101 0.5559,3.90059 1.66877,10.5775 0.59175,11.17379 -1.22072,-0.14551 -2.63702,-8.5512 -4.32193,-12.5705 -1.71471,-4.09087 -2.35814,-8.78343 -3.9690197,-13.03609 -0.94279,-2.48984 -2.3781498,-7.59402 -6.0915848,-5.57217 -2.49639996,1.35933 -2.53596996,4.99594 -2.24545996,7.43447 0.80869996,6.78077 2.45543996,13.40854 4.11661496,20.0197 3.0201798,12.02344 3.0495098,24.52226 5.2595898,36.78036 2.7301297,15.141875 7.7173597,28.576485 7.7173597,44.229555"
                                        id="left-outline"/>
                                </svg>
                            </label>
                            <div class="text-center my-3">
                                <input type="radio" class="d-none" id="left" value="left" name="hand">
                                Left hand
                            </div>
                        </div>

                        <div class="d-flex flex-column">
                            <label for="right" class="hand">
                                <svg version="1.1" name="svg-hands" id="right-hand-svg" width="217" height="294" viewBox="0 0 106.38618 141.13435" xmlns="http://www.w3.org/2000/svg">
                                    <defs>
                                        <filter style="color-interpolation-filters:sRGB"
                                            id="right-selection-filter"
                                            x="-0.028983135"
                                            y="-0.021539411"
                                            width="1.0579988"
                                            height="1.0430788">
                                            <feGaussianBlur stdDeviation="0.58994719" />
                                        </filter>
                                    </defs>
                                    <path
                                        style="mix-blend-mode:normal;fill:none;stroke:#EB6152;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:none;stroke-opacity:0.368293;filter:url(#right-selection-filter)"
                                        class="d-none"
                                        d="m 48.045615,137.82398 c -0.045,-16.28842 -9.85405,-24.40093 -21.64085,-37.30686 -2.96167,-3.242875 -3.52674,-6.687915 -6.15209,-10.205705 -3.10304,-4.15782 -7.64649,-9.24314 -10.10005,-13.81506 -1.8842898,-3.51127 -4.9666598,-4.10463 -7.2905298,-7.14637 l 0.4658,-0.93162 c 2.14751,-3.9128 5.75094,-4.03288 9.5565598,-2.67411 7.08654,2.53074 10.67117,5.61321 16.52877,13.81022 2.01457,2.81877 8.69008,3.92949 10.81069,1.7793 4.08864,-4.14579 3.61268,-10.66881 4.05534,-16.17607 1.22378,-15.22592 -2.83713,-30.34953 -0.35187,-45.64933 1.23383,-7.59616 6.22199,-11.0386199 10.09865,-6.49208 2.22034,2.60422 0.81759,8.72689 1.04863,12.08179 0.24455,3.55637 0.6526,7.18381 1.1594,10.71362 0.87899,6.1206 0.83692,17.95834 3.21488,18.85476 2.07081,-0.60478 0.95784,-9.01728 1.21544,-12.79924 0.62418,-9.1729 1.8651,-18.31651 2.718,-27.48275 0.30929,-3.32309 0.88596,-8.3666099 3.81032,-10.3678599 4.44149,-3.03985995 7.24651,0.55448 7.39705,6.6413799 0.21381,8.6021 0.004,17.46571 0.007,26.08533 0.001,3.86137 -1.59679,17.01995 -0.44629,17.61081 1.08819,-0.23113 2.25456,-12.98029 2.70313,-16.67919 0.83986,-6.92729 1.3597,-14.6335 2.5545,-21.42724 0.55292,-3.1436 3.05385,-6.01015 6.34805,-4.3896 3.92305,1.93004 3.85924,8.98654 3.41346,12.77417 -0.98193,8.35197 -0.67822,16.79411 -1.86976,25.15371 -0.55618,3.90256 -1.66962,10.58284 -0.59205,11.17943 1.22133,-0.14558 2.63835,-8.55552 4.32411,-12.57685 1.71558,-4.09293 2.35933,-8.78787 3.97103,-13.04267 0.94326,-2.4911 2.37935,-7.59786 6.094655,-5.57499 2.49767,1.36002 2.53726,4.99846 2.2466,7.43823 -0.80911,6.78419 -2.45668,13.41531 -4.118695,20.02981 -3.02171,12.02952 -3.05105,24.53465 -5.26225,36.79894 -2.73151,15.149525 -7.72126,28.590925 -7.72126,44.251905"
                                        id="right-selection"/>
                                    <path
                                        style="fill:none;stroke:#494949;stroke-width:0.999495;stroke-linecap:round;stroke-linejoin:round;stroke-dasharray:none"
                                        d="m 48.048205,137.79003 c -0.045,-16.28019 -9.84908,-24.3886 -21.62993,-37.28802 -2.96017,-3.241235 -3.52495,-6.684535 -6.14898,-10.200545 -3.10147,-4.15572 -7.64263,-9.23847 -10.09495,-13.80809 -1.8833328,-3.50949 -4.9641468,-4.10255 -7.2868428,-7.14276 l 0.465565,-0.93115 c 2.146425,-3.91082 5.748028,-4.03084 9.5517278,-2.67276 7.08296,2.52947 10.66578,5.61038 16.52042,13.80325 2.01356,2.81735 8.6857,3.92751 10.80524,1.7784 4.08657,-4.1437 3.61085,-10.66342 4.05329,-16.1679 1.22316,-15.21823 -2.8357,-30.3342 -0.35169,-45.62628 1.2332,-7.59232 6.21884,-11.0330399 10.09356,-6.4888 2.21921,2.60291 0.81717,8.72248 1.0481,12.07569 0.24442,3.55457 0.65227,7.18018 1.15881,10.70821 0.87855,6.11751 0.8365,17.94927 3.21326,18.84524 2.06976,-0.60448 0.95735,-9.01273 1.21482,-12.79278 0.62387,-9.16827 1.86416,-18.30726 2.71663,-27.46887 0.30913,-3.32141 0.88551,-8.3623899 3.8084,-10.3626199 4.43924,-3.03833 7.24285,0.5542 7.39331,6.6380199 0.2137,8.59776 0.004,17.45689 0.007,26.07216 0.001,3.85942 -1.59599,17.01135 -0.44607,17.60192 1.08764,-0.23102 2.25342,-12.97374 2.70177,-16.67077 0.83943,-6.92379 1.35901,-14.62611 2.55321,-21.41642 0.55264,-3.14201 3.05231,-6.00712 6.34484,-4.38738 3.92107,1.92906 3.85729,8.982 3.41174,12.76771 -0.98144,8.34776 -0.67788,16.78563 -1.86882,25.14101 -0.5559,3.90059 -1.66877,10.5775 -0.59175,11.17379 1.22072,-0.14551 2.63702,-8.5512 4.32193,-12.5705 1.71471,-4.09087 2.35814,-8.78343 3.96902,-13.03609 0.94279,-2.48984 2.37815,-7.59402 6.091585,-5.57217 2.4964,1.35933 2.53597,4.99594 2.24546,7.43447 -0.8087,6.78077 -2.45544,13.40854 -4.116615,20.0197 -3.02018,12.02344 -3.04951,24.52226 -5.25959,36.78036 -2.73013,15.141875 -7.71736,28.576485 -7.71736,44.229555"
                                        id="right-outline"/>
                                </svg>
                            </label>
                            <div class="text-center my-3">
                                <input type="radio" class="d-none" id="right" value="right" name="hand">
                                Right hand
                            </div>
                        </div>
                    </div>

                    <input type="hidden" name="tskin_name" value="{{ tskin_name }}">
                    <input type="hidden" name="tskin_mac" value="{{ tskin_mac }}">
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-center gap-3">
                        <a href="{{ url_for('main.index') }}" class="btn btn-outline-secondary px-4">Go back</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


{% endblock %}
{% block script %}
<script>
    $(function(){
        // on dom load
        $("input:radio[name=hand]").change(function(e){
            $("[id$=-selection]").addClass("d-none");
            
            $("#" + this.id + "-selection").removeClass("d-none")
            $("body").addClass("on_loading");
            $("#hand_form").submit();
        })
    })
</script>
{% endblock %}

tactigon_shapes/modules/tskin/templates/tskin/model.jinja
{% extends "base.jinja" %}

{% block style %}
    <style>
        #model_list {
            max-width: 300px;
        }
    </style>
{% endblock %}

{% block body %}
<div class="d-flex flex-fill scrollarea">
    <div class="container my-3">
        <form id="model_form" action="{{ url_for('tskin.save') }}" method="POST">
            <div class="card">
                <div class="card-header">
                    Tactigon Skin configuration
                </div>
                <div class="card-body">
                    <h3 class="text-center">MODEL SELECTION</h3>
                    <h5 class="text-muted text-center">Which gesture model do you want to use?</h5>
                    <hr>

                    <div class="list-group m-auto mb-3" id="model_list">
                        {% for model in models %}
                            <button type="button" class="list-group-item list-group-item-action" data-value="{{ model.name }}">{{ model.name.replace("_", " ") }}</button>
                        {% endfor %}
                    </div>

                    <input type="hidden" name="tskin_name" value="{{ tskin_name }}">
                    <input type="hidden" name="tskin_mac" value="{{ tskin_mac }}">
                    <input type="hidden" name="hand" value="{{ hand }}">
                    <input type="hidden" name="model" value="">
                </div>
                <div class="card-footer">
                    <div class="d-flex justify-content-center gap-3">
                        <a href="{{ url_for('main.index') }}" class="btn btn-outline-secondary px-4">Go back</a>
                        <button type="submit" class="btn btn-tskin" id="continue">Confirm</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    $(function(){
        // on dom load
        $("#model_list").find("button").click(function(e){
            const btn = $(this),
                model = btn.data("value");

            btn.siblings().removeClass("bg-light");
            btn.addClass("bg-light")
            $("input[name=model]").val(model);
        })
    })

</script>
{% endblock %}