tactigon_shapes/modules/zion/models.py
from enum import Enum
from dataclasses import dataclass

from typing import Optional, Any

class Scope(Enum):
    SERVER = "SERVER_SCOPE"
    CLIENT = "CLIENT_SCOPE"
    SHARED = "SHARED_SCOPE"

class AlarmStatus(Enum):
    CLEARED_UNACK = "CLEARED_UNACK"

class AlarmSearchStatus(Enum):
    ACK = "ACK"
    ACTIVE = "ACTIVE"
    ANY = "ANY"
    CLEARED = "CLEARED"
    UNACK = "UNACK"

class AlarmSeverity(Enum):
    ANY = ""
    CRITICAL = "CRITICAL"

@dataclass
class Id:
    entityType: str
    id: str

@dataclass
class Device:
    id: Id
    name: str
    type: str
    tenantId: Id
    customerId: Id

    @classmethod
    def FromZION(cls, json):
        return cls(
            Id(json["id"]["entityType"],json["id"]["id"]),
            json["name"],
            json["type"],
            Id(json["tenantId"]["entityType"],json["tenantId"]["id"]),
            Id(json["customerId"]["entityType"],json["customerId"]["id"]),
        )

    def to_alarm(self) -> dict:
        return {
            "tenantId": {
                "entityType": self.tenantId.entityType,
                "id": self.tenantId.id
            },
            "customerId": {
                "entityType": self.customerId.entityType,
                "id": self.customerId.id
            },
            "originator": {
                "entityType": self.id.entityType,
                "id": self.id.id
            }
        }

@dataclass
class ZionConfig:
    username: str
    password: str
    url: str = "https://zion.nextind.eu/"
    token: Optional[str] = None

    @classmethod
    def Default(cls):
        return cls(
            "",
            "",
            ZionConfig.url
        )

    @classmethod
    def FromJSON(cls, json: dict):
        return cls(
            json["username"],
            json["password"],
            json["url"] if "url" in json and json["url"] else cls.url
        )
    
    def toJSON(self) -> object:
        return {
            "username": self.username,
            "password": self.password,
            "url": self.url
        }

tactigon_shapes/modules/zion/blueprint.py
from tabnanny import check
from flask import Blueprint, redirect, render_template, flash, url_for

from .manager import get_zion_interface
from .models import ZionConfig

from ...config import app_config, check_config
from ...utils.request_utils import get_from_request

bp = Blueprint("zion", __name__, url_prefix="/zion", template_folder="templates", static_folder="static")

@bp.route("/")
@check_config
def index(edit: bool = False):
    app = get_zion_interface()

    if not app:
        flash("Zion interface not running", category="danger")
        return redirect(url_for("main.index"))
    
    if not app.config:
        config = ZionConfig.Default()
        edit = True
    else:
        config = app.config
    
    return render_template("zion/index.jinja", configured=app.configured, config=config, edit=edit, devices=app.devices)

@bp.route("/edit")
@check_config
def edit():
    app = get_zion_interface()

    if not app:
        flash("Zion interface not running", category="danger")
        return redirect(url_for("main.index"))
    
    return index(True)

@bp.route("/save", methods=["POST"])
@check_config
def save():
    app = get_zion_interface()

    if not app:
        flash("Zion interface not running", category="danger")
        return redirect(url_for("main.index"))
    
    username = get_from_request("username")
    password = get_from_request("password")
    url = get_from_request("url")

    if not username or not password:
        flash("Cannot save Zion configurations. Username or password are required", category="danger")
        return redirect(url_for("zion.index"))
    
    _url = url if url else ZionConfig.url

    token = app.refresh_token(_url, username, password)

    if not token:
        flash("Cannot save Zion configurations. Username or password or url are incorrect", category="danger")
        return redirect(url_for("zion.index"))
    
    new_config = ZionConfig(username, password, _url, token)
    app.save_config(new_config)

    flash("Zion configured succesfully", category="success")
    return redirect(url_for("zion.index"))


@bp.route("/remove")
@check_config
def remove():
    app = get_zion_interface()

    if not app:
        flash("Zion interface not running", category="danger")
        return redirect(url_for("main.index"))
       
    app.reset_config()

    flash("Zion configuration removed", category="success")
    return redirect(url_for("zion.edit"))

@bp.route("/devices/refresh")
@check_config
def refresh_devices():
    app = get_zion_interface()

    if not app:
        flash("Zion interface not running", category="danger")
        return redirect(url_for("main.index"))
    
    app.get_devices()

    flash(F"Zion device list refreshed ({len(app.devices)} loaded)", category="success")
    return redirect(url_for("zion.index"))

tactigon_shapes/modules/zion/templates/zion/index.jinja
{% extends "base.jinja" %}

{% block style %}
{% endblock %}

{% block body %}
<div class="d-flex flex-fill scrollarea">
    <div class="container my-3">
        <div class="card">
            <div class="card-header">
                Zion configurations
            </div>
            <div class="card-body pb-4">
                <div class="d-flex flex-column align-items-stretch gap-3">
                    <div class="d-flex justify-content-center">
                        <i class="mi-outlined mi-cloud" style="font-size: 124px"></i>
                    </div>
                    
                    <h3 class="text-center">Zion cloud</h3>
                    {% if edit %}
                        <form action="{{ url_for('zion.save') }}" method="POST">
                            <div class="mb-3">
                                <label for="username" class="form-label">Username</label>
                                <input type="text" class="form-control" id="username" name="username" value="{{ config.username if config else ''}}">
                            </div>
                            <div class="mb-3">
                                <label for="password" class="form-label">Password</label>
                                <input type="password" class="form-control" id="password" name="password" value="{{ config.password if config else ''}}">
                            </div>
                            <div class="mb-3">
                                <label for="url" class="form-label">Url</label>
                                <input type="text" class="form-control" id="url" name="url" value="{{ config.url if config else ''}}">
                            </div>
                            <div>
                                <button type="submit" class="btn btn-primary btn-block">Save</button>
                            </div>
                        </form>
                    {% else %}
                        <div class="modal fade" id="remove_zion" tabindex="-1">
                            <div class="modal-dialog">
                                <div class="modal-content text-dark">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="staticBackdropLabel">Zion</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body d-flex flex-column gap-3">
                                        <h4>Warning!</h4>
                                        You are about to cancel Zion configuration. Are you sure?
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Close</button>
                                        <a href="{{ url_for('zion.remove')}}" class="btn btn-primary">
                                            Remove
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="d-flex gap-3">
                            <p>
                                <b>Username</b>: {{ config.username }} <br>
                                <b>Password</b>: {{ config.password }} <br>
                                <b>URL</b>: {{ config.url }} <br>
                            </p>
                            <div>
                                <a href="{{ url_for('zion.edit') }}" class="btn btn-link" title="Edit parameters">
                                    <i class="bi bi-pencil"></i>
                                </a>
                                <button type="button" class="btn btn-link" data-bs-toggle="modal" data-bs-target="#remove_zion" title="Delete configuration">
                                    <i class="bi bi-trash text-danger"></i>
                                </button>
                            </div>
                        </div>
                        <h6>Devices</h6>
                        <table class="table table-sm">
                            <thead>
                                <tr>
                                    <td>Id</td>
                                    <td>Name</td>
                                </tr>
                            </thead>
                            <tbody>
                                {% for d in devices %}
                                    <tr>
                                        <td>{{ d.id.id }}</td>
                                        <td>{{ d.name }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        <a href="{{ url_for('zion.refresh_devices') }}" class="btn btn-primary btn-block">Refresh device list</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}