tactigon_shapes/main.py
from functools import wraps
from flask import Blueprint, render_template, flash, redirect, url_for, current_app

from . import __version__

from .config import check_config
from .modules.socketio import get_socket_app
from .utils.extensions import stop_apps

from .modules.tskin.manager import stop_tskin

bp = Blueprint('main', __name__, template_folder="main")

# @bp.before_request
# def manage():
#     socket_app = get_socket_app()
#     if socket_app:
#         socket_app.send_data(False)
#         socket_app.send_gesture(False)
#         socket_app.send_voice(False)

@bp.route("/", methods=["GET"])
@check_config
def index():
    return redirect(url_for("shapes.index"))

@bp.route("/settings")
def settings():
    return render_template("info.jinja", version=__version__)

@bp.route("/quit")
def quit():
    stop_apps()
    stop_tskin()

    app = get_socket_app()
    if app and app.is_running:
        app.stop()

    return "ok"

tactigon_shapes/modules/tskin/blueprint.py
import sys
import json
import asyncio
from os import path
from bleak import BleakScanner
from flask import Blueprint, render_template, redirect, url_for, request, flash, current_app
from typing import Optional

from .manager import get_tskin_default_config, get_voice_default_config, start_tskin, load_tskin, stop_tskin, get_tskin
from .models import TSkinModel, VoiceConfig, TSkinConfig, Hand, GestureConfig, TSpeechObject, TSpeech, HotWord

from ..socketio import get_socket_app
from ...config import app_config
from ...utils.extensions import stop_apps
from ...utils.request_utils import get_from_request

bp = Blueprint('tskin', __name__, url_prefix="/tskin", template_folder="templates")

@bp.before_request
def manage():
    stop_apps()

@bp.route("add", methods=["GET"])
def add():
    return render_template("tskin/add.jinja")

if sys.platform == "darwin":
    @bp.route("scan", methods=["GET"])
    def scan():
        async def find_devices():
            devices = await BleakScanner.discover(cb=dict(use_bdaddr=True))
            return filter(lambda d: str(d.name).startswith("TSKIN") or str(d.name).startswith("TACTI"), devices)

        devices = asyncio.run(find_devices())
        tskins = [{"name": d.name, "id": d.address, "address": str(d.details[0].identifier())} for d in devices]
        
        return json.dumps(tskins)
else:
    @bp.route("scan", methods=["GET"])
    def scan():
        async def find_devices():
            devices = await BleakScanner.discover()
            return filter(lambda d: str(d.name).startswith("TSKIN") , devices)

        devices = asyncio.run(find_devices())
        tskins = [{"name": d.name, "id": d.address, "address": d.address} for d in devices]

        return json.dumps(tskins)

@bp.route("hand", methods=["POST"])
def hand():
    tskin_name = get_from_request("tskin_name")
    tskin_mac = get_from_request("tskin_mac")

    if not (tskin_mac and tskin_name):
        flash("You need to select a Tactigon Skin to proceed", category="danger")
        return redirect(url_for("tskin.add"))

    return render_template("tskin/hand.jinja", tskin_name=tskin_name, tskin_mac=tskin_mac)

@bp.route("model", methods=["POST"])
def model():
    tskin_name = get_from_request("tskin_name")
    tskin_mac = get_from_request("tskin_mac")

    if not tskin_name or not tskin_mac:
        return redirect(url_for("tskin.add"))

    hand = get_from_request("hand")

    if not hand:
        flash("Please select a hand", "danger")
        return redirect(url_for("tskin.add"))

    models = list(filter(lambda m: m.hand.value==hand, app_config.MODELS))

    if len(models) == 1:
        return redirect(url_for("tskin.save", tskin_name=tskin_name, tskin_mac=tskin_mac, hand=hand, model=models[0].name), code=307)

    return render_template("tskin/model.jinja", tskin_name=tskin_name, tskin_mac=tskin_mac, hand=hand, models=models)

@bp.route("/remove", methods=["GET"])
def remove():
    socket_app = get_socket_app()

    tskin = get_tskin()

    if tskin is None:
        flash(F"Tactigon skin {hand} not configured!", "danger")
        return redirect(url_for("main.index"))

    if socket_app:
        socket_app.stop()
    
    stop_tskin()

    app_config.TSKIN = None
    app_config.TSKIN_VOICE = None
    
    app_config.save()
    current_app.config.from_object(app_config)

    if socket_app:
        socket_app.init_app(current_app)

    return redirect(url_for("main.index"))

@bp.route("save", methods=["POST"])
def save():
    socket_app = get_socket_app()

    tskin_name = get_from_request("name")
    tskin_mac = get_from_request("mac")

    if not tskin_name or not tskin_mac:
        flash("Please select a Tactigon Skin", "danger")
        return {"error": "name or mac error"}, 500

    hand = get_from_request("hand")
    
    if not hand:
        flash("Please select a hand", "danger")
        return {"error": "hand error"}, 500

    # if not model_name:
    #     flash("Please select a model", "danger")
    #     return redirect(url_for("tskin.add", tskin_name=tskin_name, tskin_mac=tskin_mac, hand=hand), code=307)
        
    hand = Hand(hand)
    model_name = "MODEL_01_" + hand.name

    current_model: Optional[TSkinModel] = None

    for model in app_config.MODELS:
        if model.name == model_name:
            current_model = model
            break

    if current_model is None:
        flash("Error MODEL", "danger")
        return {"error": "model error"}, 500
        # return redirect(url_for("tskin.add"))
    
    tskin_config = get_tskin_default_config(tskin_mac, hand, tskin_name, current_model)
    voice_config = get_voice_default_config()

    if voice_config:
        voice_config.stop_hotword = None

    if socket_app:
        socket_app.stop()

    stop_tskin()
    app_config.TSKIN = tskin_config
    app_config.TSKIN_VOICE = voice_config

    app_config.save()
    current_app.config.from_object(app_config)

    load_tskin(tskin_config, voice_config)
    tskin = start_tskin()

    if socket_app and tskin:
        socket_app.setTSkin(tskin)

    return json.dumps(tskin_config.toJSON()), 200

if sys.platform != "darwin":
    @bp.route("play", methods=["POST"])
    def play(base_path = ""):
        tskin = get_tskin()

        if not tskin:
            return "Error: TSkin not present"
        
        data = request.get_json(force=True)

        if not data:
            return "Error: No JSON in request"
        
        audio_file = data.get("audio_file")

        if not audio_file:
            return "Error: No audio_file in JSON"
        
        base_path = data.get("base_path")

        if base_path:
            audio_file = path.join(base_path, audio_file)

        tskin.play(audio_file)

        return "Ok"
else:
    @bp.route("play", methods=["POST"])
    def play(base_path = ""):
        return "Not Implemented", 500

tactigon_shapes/templates/base.jinja
{% macro tskin_panel(config) %}
<div class="d-flex justify-content-between align-items-center gap-3">
    <div class="d-flex gap-3 align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" class="bi bi-tskin align-self-center text-light"
            viewBox="0 0 40 40">
            <path fill="#000" fill-rule="evenodd" clip-rule="evenodd"
                d="M0.765806 12.4697C5.3185 11.1389 14.901 9 24.3289 9C37.159 9 40 12.4225 40 20.7885C40 28.6791 40 30.9608 34.6414 30.9608H6.91656C1.96779 30.9608 -1.1481 19.6477 12.6901 19.6477H32.027C36.5175 19.6477 36.6092 13.3731 32.4852 12.2323C28.4499 11.116 16.0789 10.5459 1.38217 14.6189C0.833908 14.7709 0.260099 14.4671 0.0661623 13.9138C-0.145839 13.309 0.168707 12.6443 0.765806 12.4697ZM38.1239 25.732L4.94877 25.732V26.3024C4.94877 27.8776 6.17968 29.1545 7.69809 29.1545L35.3745 29.1545C36.8929 29.1545 38.1239 27.8776 38.1239 26.3024V25.732Z"
                fill="#121212"></path>
        </svg>
        <h6 class="mb-0 text-uppercase">{{ config.name }}</h6>
        <!--<small class="mb-0 opacity-75">{{ config.address }}</small>-->
        <i class="bi bi-bluetooth align-self-center" style="font-size: 24px; color: #0d6efd"></i>
        {# <div>
            <button type="button" class="btn btn-link text-light" {% if not connected %} disabled {% endif %}>
                <i class="bi bi-three-dots-vertical"></i>
            </button>
        </div> #}
    </div>

    <img src="{{ url_for('static', filename='images/' + config.hand.value + '-hand.svg') }}" height="45">

    <button type="button" class="btn btn-link tskin float-end" data-bs-toggle="modal"
        data-bs-target="#removetskinmodal_{{config.hand.value}}">
        <i class="bi bi-x-circle" style="font-size: 24px;"></i>
    </button>

    <!--
        <div class="btn-group-vertical">
            <button type="button" class="btn {% if hand == 'left' %} btn-primary {% else %} btn-outline-primary {% endif %}" {% if not connected %} disabled {% endif %}>
                <img src="{{ url_for('static', filename='images/left_stroke.png') }}" alt="twbs" width="24" height="24">
            </button>
            <button type="button" class="btn {% if hand == 'right' %} btn-primary {% else %} btn-outline-primary {% endif %}" {% if not connected %} disabled {% endif %}>
                <img src="{{ url_for('static', filename='images/right_stroke.png') }}" alt="twbs" width="24" height="24">
            </button>
        </div>
        -->
</div>
{% endmacro %}

{% macro tskin_management(config) %}
<div class="modal fade" id="removetskinmodal_{{config.hand.value}}" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content text-dark">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Tactigon skin {{config.hand.value}}</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body d-flex flex-column gap-3">
                <h4>Warning!</h4>
                You are about to remove {{ config.name }}. Are you sure?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Close</button>
                <a href="{{ url_for('tskin.remove', hand=config.hand.value)}}" class="btn btn-primary">
                    Remove
                </a>
            </div>
        </div>
    </div>
</div>
{% endmacro%}

{% macro side_panel_right() %}
{% if tskin_config %}
{{ tskin_management(tskin_config) }}
{% endif %}

<div class="offcanvas offcanvas-end" id="panel_device_connection" data-bs-scroll="true" data-bs-backdrop="false"
    tabindex="-1">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasScrollingLabel">Device connection</h5>
        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <hr>
        <div class="d-flex flex-column gap-3">
            {% if tskin_config %}
            {{ tskin_panel(tskin_config) }}
            {% endif %}

            {#
            <a href="{{ url_for('tskin.add') }}" class="btn btn-light gap-3">
                <i class="bi bi-plus"></i>
                Add
            </a>
            #}
        </div>
    </div>
</div>
{% endmacro %}

{% macro popup_message(messages) %}
<div class="toast-container end-0 p-3">
    {% for category, message in messages %}
    <div class="toast {{ category }}" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header bg-primary bg-{{ category }} bg-opacity-50">
            <strong class="me-auto">
                {% if category == 'success' %}
                Success
                {% elif category == 'warning' %}
                Warning
                {% elif category == 'danger' %}
                Error
                {% else %}
                Info
                {% endif %}
            </strong>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div class="toast-body">
            {{ message }}
        </div>
    </div>
    {% endfor %}
</div>
{% endmacro %}

{% macro tskin(config) %}
<div id="tskin-management" class="d-flex gap-3 m-2">
    <div class="d-flex gap-1">
        <img src="{{ url_for('static', filename='images/' + config.hand.value + '.png') }}" alt="twbs" width="20" height="20">
        <small>{{ config.hand.value[0].upper() }}</small>
    </div>
    <div class="d-flex gap-1">
        <img src="{{ url_for('static', filename='images/tactigon.png') }}" alt="twbs" width="20" height="20">
        <small>{{ config.name.upper() }}</small>
    </div>
    <div class="d-flex gap-1">
        <i class="mi-round mi-bluetooth-connected connected d-none" style="font-size: 20px; color: #fff"></i>
        <i class="mi-round mi-bluetooth disconnected d-none" style="font-size: 20px; color: gray"></i>
    </div>
    <div class="d-flex gap-1 battery-container d-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="align-self-center"
            viewBox="0 0 16 16">
            <path id="battery-perc" d="M2 6h0v4H2z" />
            <path
                d="M2 4a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V6a2 2 0 0 0-2-2zm10 1a1 1 0 0 1 1 1v4a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1zm4 3a1.5 1.5 0 0 1-1.5 1.5v-3A1.5 1.5 0 0 1 16 8" />
        </svg>
        <small class="align-self-center" id="battery-voltage"></small>
    </div>
</div>
{% endmacro %}

{% macro braccio(config) %}
<div id="braccio-management" class="d-flex gap-3 m-2">
    <div class="gap-1">
        <i class="mi-round mi-precision-manufacturing" style="font-size: 20px;"></i>
        {% if config %}
            <small>{{ config.name }}</small>
        {% else %}
            <small style="color: gray;">Not configured</small>
        {% endif %}
    </div>
    {% if config %}
        <div>
            <i class="mi-round mi-bluetooth-connected connected d-none" style="font-size: 20px; color: #fff;"></i>
            <i class="mi-round mi-bluetooth disconnected" style="font-size: 20px; color: gray;"></i>
        </div>
    {% endif %}
</div>
{% endmacro %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tactigon Shapes</title>
    <link rel="shortcut icon" href="{{ url_for('favicon') }}">
    <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/bootstrap-icons.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/material-icons.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
    {% block style %}
    {% endblock %}
</head>

<body class="">
    <!--- Loader --->
    <div class="d-flex" id="loading_spinner">
        <div class="d-flex flex-fill justify-content-center align-self-center">
            <div class="spinner-border spinner-lg tskin" role="status">
                <span class="visually-hidden">Loading...</span>
            </div>
        </div>
    </div>
    <!--- Navbar TSKIN status -->
    <div class="sticky-top">
        <nav class="bg-dark text-light">
            <div class="container-fluid d-flex justify-content-end align-items-center gap-3">
                | {{ braccio(braccio_config) }} | {{tskin(tskin_config)}}
            </div>
        </nav>
        <!--- Navbar app -->
        <nav class="navbar bg-tskin">
            <div class="container-fluid">
                <a href="{{ url_for('shapes.index') }}" class="btn btn-link text-decoration-none text-light" title="Shapes">
                    <i class="mi-round mi-extension" style="font-size: 24px"></i>
                </a>
                <div>
                    <a href="{{ url_for('zion.index') }}" class="btn btn-link text-decoration-none text-light" title="Zion cloud">
                        <i class="mi-outlined mi-cloud" style="font-size: 24px"></i>
                    </a>
                    {% if has_braccio %}
                        <a href="{{ url_for('braccio.index') }}" class="btn btn-link text-decoration-none text-light" title="Braccio">
                            <i class="mi-round mi-precision-manufacturing" style="font-size: 24px"></i>
                        </a>
                    {% endif %}
                    <button class="btn btn-link text-decoration-none text-light" title="Tactigon Skin"
                        data-bs-toggle="offcanvas" data-bs-target="#panel_device_connection"
                        aria-controls="offcanvasScrolling">
                        <img src="{{ url_for('static', filename='images/tactigon.png') }}" width="24" height="24">
                    </button>
                    <a href="{{ url_for('main.settings') }}" class="btn btn-link text-decoration-none text-light" title="Settings">
                        <i class="mi-round mi-settings" style="font-size: 24px"></i>
                    </a>
                </div>
            </div>
        </nav>
    </div>

    {{ side_panel_right() }}

    {% with messages = get_flashed_messages(with_categories=true) %}
    {{ popup_message(messages) }}
    {% endwith %}

    <main>
        {% block body %}{% endblock %}
    </main>

    <script src="{{url_for('static', filename='js/jquery-3.6.3.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/bootstrap.bundle.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/socket.io-4.7.2.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/svg.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/main.js')}}"></script>
    {% block script %}{% endblock %}
</body>

</html>

tactigon_shapes/templates/error.jinja
{% extends "base.jinja" %}
{% block style %}
{% endblock %}
{% block body %}
    <div class="container p-4">
        <div class="d-flex flex-column align-items-center justify-content-center m-3 gap-2">
            <img src="{{ url_for('static', filename='images/error.gif') }}" width="300px">
            <h4>OPS! An error occurred...</h4>
            <p>
                <b>Url: </b>[{{ method | upper }}]{{ url | safe}}.<br/>
                <b>Args: </b>{{ args | safe }}<br/>
                <b>Form: </b>{{ form | safe }}<br/>
                <b>Error: </b>{{ error | safe}}.
            </p>
            <p>
                Please send this screenshot to a <a href="mailto:developer@nextind.eu">developer</a>, hopefully we can reproduce the error and help you!
            </p>
            <p>
                In the meantime, you can
            </p>
            <a href="{{ url_for('main.index') }}" class="btn btn-primary">Go back</a>
        </div>
    </div>
{% endblock %}

tactigon_shapes/templates/info.jinja
{% extends "settings.jinja" %}

{% block settings %}
    <div class="container p-3">
        <div class="card m-auto w-50">
            <div class="card-body">
                <div class="d-flex flex-column align-content-center text-center gap-3">
                    <img src="{{ url_for('static', filename='images/logo.png') }}" class="mx-auto d-block my-4" height="80px" width="80px">
                    <p class="h3">Tactigon Shapes</p>
                    <p>Version: {{ version }}</p>
                    {% if tskin_config %}
                        <p class="h3">Tactigon Skin</p>
                        <p class="mx-auto text-start">
                            Name: {{ tskin_config.name }}<br/>
                            Bluetooth: {{ tskin_config.address }}<br/>
                            Hand: {{ tskin_config.hand.name }}<br/>
                            Model: {{ tskin_config.gesture_config.name}}<br/>
                            Firmware: v5.0.3<br/>
                            Tactigon Gear: v{{ tactigon_gear }}<br/>
                            {% if tactigon_speech %}
                                Tactigon Speech: v{{ tactigon_speech }}
                            {% endif %}
                        </p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    
{% endblock settings %}

tactigon_shapes/templates/settings.jinja
{% extends "base.jinja" %}

{% block body %}
    <div class="d-flex flex-fill">
        <div class="d-flex flex-column justify-content-between sidebar-container">
            <div class="text-center pt-5 pb-3">
                <h5>Settings</h5>
            </div>

            <div class="list-group list-group-flush flex-grow-1 sidebar">
                <a href="{{ url_for('main.settings') }}" class="list-group-item list-group-item-action {% if 'settings' in request_path %}active{% endif %}" alt="Notification's settings">
                    <i class="bi bi-info-circle px-3"></i>
                    Info
                </a>
            </div>
        </div>
        {% block settings %}
        {% endblock%}
    </div>
{% endblock %}